version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project/docker_practice/
permissions:
  - object: /
    owner: root
    group: root
    mode: 777
hooks:
  ApplicationStop:
  - location: /home/ec2-user/project/docker_practice/stop_server.sh
    timeout: 300
    runas: root
  ApplicationStart:
    - location: /home/ec2-user/project/docker_practice/start_server.sh
      timeout: 300
      runas: root