version: 0.0
os: linux
files:
  - source: /
    destination: /
permissions:
  - object: /
    owner: root
    group: root
    mode: 777
hooks:
  # ApplicationStop:
  # - location: /script/stop_server.sh
  #   timeout: 300
  #   runas: root
  AfterInstall:
    - location: /opt/codedeploy-agent/deployment-root/39004a29-79f5-4775-895b-3bfc3b3b5e86/d-98F18KED5/deployment-archive/scripts/start_server.sh
      timeout: 30
      runas: root