version: 0.0
os: linux
files:
  - source: /
    destination: /project
permissions:
  - object: /
    owner: root
    group: root
    mode: 777
hooks:
  ApplicationStop:
  - location: ./scripts/stop_server.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: ./scripts/start_server.sh
    timeout: 3000
    runas: root