version: 0.0
os: linux
files:
  - source: /
    destination: /
permissions:
  - object: /
    owner: root
    group: root
    mode: 777
hooks:
  ApplicationStop:
  - location: /script/stop_server.sh
    timeout: 300
    runas: root
  AfterInstall:
    - location: /script/start_server.sh
      timeout: 300
      runas: root