version: 0.0
os: linux
files:
  - source: /
    destination: ~/project/docker_practice/
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 777
hooks:
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
    runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user