version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z9h6z8
  build:
    commands:
      - docker build -t to_do_frontend:latest ./frontend/
      - docker tag to_do_frontend:latest public.ecr.aws/s0z9h6z8/to_do_frontend:latest

  post_build:
    commands:
      - docker push public.ecr.aws/s0z9h6z8/to_do_frontend:latest
      - printf '[{"name":"frontend","imageUri":"public.ecr.aws/s0z9h6z8/to_do_frontend"}]' public.ecr.aws/s0z9h6z8/to_do_frontend:latest > $CODEBUILD_SRC_DIR/imagedefinitionsfrontend.json
      - aws ecs describe-task-definition --task-definition to_do_frontend --region us-east-1 | jq .taskDefinition > taskdeffrontend.json
      - cat taskdef.json | jq 'walk(if type == "array" and length == 0 then null else . end)' > taskdef.json

artifacts:
  files:
    - taskdeffrontend.json
    - appspec.yaml
    - imagedefinitionsfrontend.json