version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-authorization-token --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s0z9h6z8
  build:
    commands:
      - docker build -t to_do_backend:latest ./backend/
      - docker tag to_do_backend:latest public.ecr.aws/s0z9h6z8/to_do_backend:latest
  post_build:
    commands:
      - docker push public.ecr.aws/s0z9h6z8/to_do_backend:latest