services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INIT_ROOT_USERNAME=root
      - MONGO_INIT_ROOT_PASSWORD=password
    networks:
      - mongo_net
    volumes:
      - mongo_data:/data/db
    container_name: mongodb


  backend:
    image: public.ecr.aws/s0z9h6z8/to_do_backend:latest
    ports:
      - 8000:8000
    networks:
      - mongo_net
    depends_on:
      - mongodb
    container_name: backend

  frontend:
    image: public.ecr.aws/s0z9h6z8/to_do_frontend:latest
    ports:
      - 80:3000
    networks:
      - mongo_net
    depends_on:
      - mongodb
      - backend
    container_name: frontend

networks:
  mongo_net:

volumes:
  mongo_data:
